package com.quizmania.repository;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "User")
public class User {

  private String userId;
  private String firstName;
  private String userName;
  

public String getUserName() {
	return userName;
}

public String getPassword() {
	return password;
}

private String lastName;
  private String password;
  
  public User (String firstname, String lastname){
	  this.firstName=firstname;
	  this.lastName=lastname;
  }
  
  @DynamoDBHashKey
  @DynamoDBAutoGeneratedKey 
  public String getUserId()
  {
    return userId;
  }

  @DynamoDBAttribute
  public String getFirstName()
  {
    return firstName;
  }

  @DynamoDBAttribute
  public String getLastName()
  {
    return lastName;
  }

  // setters, default constructor and firstname/lastname constructor
}
