package com.quizmania.repository;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.quizmania.auth.Role;

@DynamoDBTable(tableName = "User")
public class User{


	private String id;
	private String userName;
	private String firstName;
	private String email;
	private String lastName;
	private String password;
	private Role role;
	
	public String getPassword() {
		return password;
	}



	public User(String firstname, String lastname) {
		this.firstName = firstname;
		this.lastName = lastname;
	}

	public User(){}
	
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@DynamoDBAttribute
	public String getFirstName() {
		return firstName;
	}

	@DynamoDBAttribute
	public String getLastName() {
		return lastName;
	}

	@Override
	public boolean equals(Object u) {
		if (u instanceof User) {
			User uu = (User) u;

			if ((id.equals(uu.id)) && (firstName.equals(uu.firstName))
					&& (lastName.equals(uu.lastName))
					&& (userName.equals(uu.userName)))
				return true;
		}

		return false;
	}

	public String getUsername() {
		return userName;
	}

	public void setUsername(String username) {
		this.userName = username;
	}


	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}



	public Role getRole() {
		return role;
	}



	public void setRole(Role role) {
		this.role = role;
	}


}
