/* 
 **
 ** Copyright 2014, Jules White
 **
 ** 
 */
package com.quizmania.repository;

import java.util.Collection;
import java.util.Collections;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.AuthorityUtils;
import org.springframework.security.core.userdetails.UserDetails;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

/*
@DynamoDBTable(tableName = "User")
public class User__ implements UserDetails {
	
	private String id;
	private String firstName;
	private String lastName;

	  @DynamoDBHashKey
	  @DynamoDBAutoGeneratedKey 
	  public String getId()
	  {
	    return id;
	  }
	
	  @DynamoDBAttribute
	  public String getFirstName()
	  {
	    return firstName;
	  }
	  
	  @DynamoDBAttribute
	  public String getLastName()
	  {
	    return lastName;
	  }
	  
	public static UserDetails create(String username, String password,
			String...authorities) {
		return new User__(username, password, authorities);
	}
	
	@DynamoDBAttribute
	private final Collection<GrantedAuthority> authorities_;
	
	private final String password_;
	private final String username_;

	@SuppressWarnings("unchecked")
	private User__(String username, String password) {
		this(username, password, Collections.EMPTY_LIST);
	}

	private User__(String username, String password,
			String...authorities) {
		username_ = username;
		password_ = password;
		authorities_ = AuthorityUtils.createAuthorityList(authorities);
	}

	private User__(String username, String password,
			Collection<GrantedAuthority> authorities) {
		super();
		username_ = username;
		password_ = password;
		authorities_ = authorities;
	}

	public Collection<GrantedAuthority> getAuthorities() {
		return authorities_;
	}

	@DynamoDBAttribute
	public String getPassword() {
		return password_;
	}
	
	@DynamoDBAttribute
	public String getUsername() {
		return username_;
	}

	@Override
	public boolean isAccountNonExpired() {
		return true;
	}

	@Override
	public boolean isAccountNonLocked() {
		return true;
	}

	@Override
	public boolean isCredentialsNonExpired() {
		return true;
	}

	@Override
	public boolean isEnabled() {
		return true;
	}

}
*/