package com.quizmania.client;



import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;


@DynamoDBTable(tableName = "Games")
public class Game {
	

	private String id;
	
	private String var1;
	private String var2;
	private String var3;
	private String var4;
	private int answer;
	private String description;
	private Integer rate;
	
	public Game(){}

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey 
	public String getGameId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBAttribute
	public String getVar1() {
		return var1;
	}

	public void setVar1(String var1) {
		this.var1 = var1;
	}
	
	@DynamoDBAttribute
	public String getVar2() {
		return var2;
	}

	public void setVar2(String var2) {
		this.var2 = var2;
	}

	@DynamoDBAttribute
	public String getVar3() {
		return var3;
	}

	public void setVar3(String var3) {
		this.var3 = var3;
	}

	@DynamoDBAttribute
	public String getVar4() {
		return var4;
	}

	public void setVar4(String var4) {
		this.var4 = var4;
	}

	@DynamoDBAttribute
	public int getAnswer() {
		return answer;
	}

	public void setAnswer(int answer) {
		this.answer = answer;
	}

	@DynamoDBAttribute
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@DynamoDBAttribute
	public Integer getRates() {
		return rate;
	}

	public void setRates(Integer rate) {
		this.rate = rate;
	}

	public boolean equalTo(Object g){
		Game r=(Game)g;
		return  (id==r.id);
		
	}
	public String toString(){
		return String.format("Game object ID:%s,\n " +
				"Question1:%s,\n" +
				"Question2:%s,\n" +
				"Question3:%s,\n" +
				"Question4:%s,\n" +
				"Answer:%s,\n" +
				"Explanation:%s,\n" +
				"Rate:%s",id,var1,var2,var3,var4,answer,description,rate);
		
	}
	
	
	public Game (String var1, String var2,String var3, String var4,
    		int answer, String description, int rates) {
		
		this.var1 = var1;
		this.var2 = var2;
		this.var3 = var3;
		this.var4 = var4;
		this.answer = answer;
		this.description = description;
		this.rate=rates;
    }

		
		
	
	
}
