package com.quizmania.client;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;


@DynamoDBTable(tableName = "Games")
public class Game {
	

	private String gameId;
	private String identificator;
	private String var1;
	private String var2;
	private String var3;
	private String var4;
	private int answer;
	private String description;
	private int rate;
	private int level;
	private String odd_Movie_String;
	private String type;
	
	public Game(){}

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	public String getGameId() {
		return gameId;
	}

	public void setGameId(String id) {
		this.gameId = id;
	}
	
	 
	public String getIdentificator() {
		return identificator;
	}

	public void setIdentificator(String identificator) {
		this.identificator = identificator;
	}

	@DynamoDBAttribute
	public String getVar1() {
		return var1;
	}

	public void setVar1(String var1) {
		this.var1 = var1;
	}
	
	@DynamoDBAttribute
	public String getVar2() {
		return var2;
	}

	public void setVar2(String var2) {
		this.var2 = var2;
	}

	@DynamoDBAttribute
	public String getVar3() {
		return var3;
	}

	public void setVar3(String var3) {
		this.var3 = var3;
	}

	@DynamoDBAttribute
	public String getVar4() {
		return var4;
	}

	public void setVar4(String var4) {
		this.var4 = var4;
	}

	@DynamoDBAttribute
	public int getAnswer() {
		return answer;
	}

	public void setAnswer(int answer) {
		this.answer = answer;
	}

	@DynamoDBAttribute
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@DynamoDBAttribute
	public int getRate() {
		return rate;
	}

	public void setRate(int rate) {
		this.rate = rate;
	}


	public int getLevel() {
		return level;
	}

	public void setLevel(int level) {
		this.level = level;
	}

	public String getOdd_Movie_String() {
		return odd_Movie_String;
	}

	public void setOdd_Movie_String(String odd_Movie_String) {
		this.odd_Movie_String = odd_Movie_String;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public boolean equals(Object g){
		Game r=(Game)g;
		return  (
				(var1.equals(r.var1))&&
				(var2.equals(r.var2))&&
				(var3.equals(r.var3))&&
				(var4.equals(r.var4))&&
				(answer==r.answer));
		
	}
	public String toString(){
		return String.format("Game object ID:%s,\n " +
				"Question1:%s,\n" +
				"Question2:%s,\n" +
				"Question3:%s,\n" +
				"Question4:%s,\n" +
				"Answer:%s,\n" +
				"Explanation:%s,\n" +
				"Rate:%s",gameId,var1,var2,var3,var4,answer,description,rate);
		
	}
	
	
	public Game (String var1, String var2,String var3, String var4,
    		int answer, String description, int rates, int level, String odd_movie, String type) {
		this.gameId=var1+var2+var3+var4;
		this.var1 = var1;
		this.var2 = var2;
		this.var3 = var3;
		this.var4 = var4;
		this.answer = answer;
		this.description = description;
		this.rate=rates;
		this.level=level;
		this.odd_Movie_String=odd_movie;
		this.type=type;
    }
		
	
	
}
