package com.quizmania.client;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Scoreboards")
public class ScoreBoard {

	private String boardId;
	private String userId;
	private String gameId;
	private int gameWin=0;
	private int gameLoss=0;
	
	//private int GameGuess=0;
	public ScoreBoard(){}
	
	public ScoreBoard(String userId, int GameWin, int GameLoss, String gameId){
		this.userId=userId;
		this.gameId=gameId;
		this.gameWin=GameWin;
		this.gameLoss=GameLoss;
	}
	
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey 
	public String getboardId(){
		return boardId;
	}
	


	public void setUserId(String userId) {
		this.userId = userId;
	}

	public void setGameId(String gameId) {
		this.gameId = gameId;
	}

	public void setboardId(String boardId) {
		this.boardId = boardId;
	}

	@DynamoDBAttribute
	public int getGameWin() {
		return gameWin;
	}

	public void setGameWin(int gameWin) {
		this.gameWin = gameWin;
	}

	@DynamoDBAttribute
	public int getGameLoss() {
		return gameLoss;
	}
	
	public void setGameLoss(int gameLoss) {
		this.gameLoss = gameLoss;
	}

	@DynamoDBAttribute
	public String getUserId() {
		return userId;
	}
	
	@DynamoDBAttribute
	public String getGameId() {
		return gameId;
	}
	
}
